name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4  # Updated to v4

      - name: Setup Node
        uses: actions/setup-node@v4  # Updated to v4
        with:
          node-version: '20'  # Specify Node version
          cache: 'npm'  # Add caching for faster installs

      - name: Install dependencies
        run: npm ci  # Use npm ci for cleaner installs

      - name: Build project
        run: npm run build
        env:
          NODE_ENV: production  # Set production environment

      - name: Setup Pages
        uses: actions/configure-pages@v3  # Configure GitHub Pages

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2  # Upload to Pages artifact
        with:
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2  # Official GitHub Pages deployment